typography_spectrum: 0.9182393404189497
color:
  brandStrength: 0.7588810990564525
  lightness: 0.8701113592833281
  saturation: 0.14655170124024153
  rhythmicContrast: 0.45313094090670347
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
layout_spectrum: 0.3829775517806411
analytics:
  google: UA-78481183-1
author:
  name: Ryan Nurmela
  email: ryannurmela@gmail.com
  url: www.poly.school
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/86f92537-04a7-45b4-b82d-dab5b9f6e20c.png
name: Poly School
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7ba4d160-2347-46de-b4a1-34d3e4fff505.png
title: Learn what you want. Teach what you want.
description: More than one way to make a school.
